import Foundation

// MARK: - Archetypes

/// The behavioural-activation domains Moth draws tasks from.
///
/// Behavioural activation treats depression by scheduling small, concrete,
/// achievable actions -- the action comes first and the motivation follows,
/// which is the reverse of what a depressed person expects. These seven
/// domains cover the activity classes BA protocols typically sample from.
public enum Archetype: String, Codable, CaseIterable, Sendable {
    case move      // get the body out of the chair
    case tend      // care for your space or your things
    case connect   // a thread back to another person
    case create    // make a mark, however small
    case sense     // ground in the physical world
    case nourish   // water, food, warmth, meds
    case rest      // wind down, breathe, close the day

    public var displayName: String {
        switch self {
        case .move: return "Move"
        case .tend: return "Tend"
        case .connect: return "Connect"
        case .create: return "Create"
        case .sense: return "Ground"
        case .nourish: return "Nourish"
        case .rest: return "Rest"
        }
    }

    /// Emoji the buddy uses when it offers this kind of task.
    public var glyph: String {
        switch self {
        case .move: return "\u{1F6B6}"
        case .tend: return "\u{1F9F9}"
        case .connect: return "\u{1F4AC}"
        case .create: return "\u{270F}\u{FE0F}"
        case .sense: return "\u{1F343}"
        case .nourish: return "\u{1F375}"
        case .rest: return "\u{1F319}"
        }
    }

    /// Archetypes that stay appropriate right up against bedtime.
    public var isWindDownSafe: Bool {
        switch self {
        case .rest, .sense, .tend, .nourish: return true
        case .move, .connect, .create: return false
        }
    }
}

// MARK: - Tasks

public enum TaskOrigin: String, Codable, Sendable {
    /// Generated by the grammar.
    case engine
    /// Typed by the user (usually with the predictor doing most of the typing).
    case user
}

public enum TaskOutcome: String, Codable, Sendable {
    case pending
    case done
    case skipped
    /// Offered but the day ended before the user answered either way.
    case expired
}

public struct MothTask: Codable, Identifiable, Equatable, Sendable {
    public let id: UUID
    /// Which grammar frame produced this, or nil for a user-written task.
    /// Kept so the engine can avoid repeating a frame within an evening.
    public let frameID: Int?
    public let text: String
    public let archetype: Archetype
    /// 1 (trivially small) ... 5 (a real push). Kept in step with `Ladder`.
    public let effort: Int
    /// Rough minutes, shown to the user so nothing feels open-ended.
    public let estimatedMinutes: Int
    public let origin: TaskOrigin
    public let offeredAt: Date
    public var outcome: TaskOutcome
    public var resolvedAt: Date?

    public init(
        id: UUID = UUID(),
        frameID: Int? = nil,
        text: String,
        archetype: Archetype,
        effort: Int,
        estimatedMinutes: Int,
        origin: TaskOrigin,
        offeredAt: Date,
        outcome: TaskOutcome = .pending,
        resolvedAt: Date? = nil
    ) {
        self.id = id
        self.frameID = frameID
        self.text = text
        self.archetype = archetype
        self.effort = Swift.min(Swift.max(effort, 1), 5)
        self.estimatedMinutes = estimatedMinutes
        self.origin = origin
        self.offeredAt = offeredAt
        self.outcome = outcome
        self.resolvedAt = resolvedAt
    }
}

// MARK: - Context

/// Coarse buckets for the time of day. The bandit keeps separate posteriors per
/// bucket, because what somebody will actually do at 3pm and at 11pm differ far
/// more than they differ between two Tuesdays.
public enum TimeBucket: String, Codable, CaseIterable, Sendable {
    case morning     // 05:00 - 11:59
    case afternoon   // 12:00 - 16:59
    case evening     // 17:00 - 20:59
    case night       // 21:00 - 04:59

    public static func from(hour: Int) -> TimeBucket {
        switch hour {
        case 5..<12: return .morning
        case 12..<17: return .afternoon
        case 17..<21: return .evening
        default: return .night
        }
    }
}

/// Everything the generator is allowed to condition on. Assembled fresh for
/// each request; deliberately small, and none of it ever leaves the device.
public struct Context: Codable, Equatable, Sendable {
    /// Self-reported right now, 1 (flattened) ... 5 (charged).
    public var energy: Int
    /// Self-reported right now, 1 (low) ... 5 (good).
    public var mood: Int
    public var timeBucket: TimeBucket
    /// Minutes until the user's stated bedtime. Negative once it has passed.
    public var minutesToBedtime: Int
    /// Fraction of offered tasks completed over the trailing window, 0...1.
    public var recentCompletionRate: Double
    public var streakDays: Int
    /// Most recent first. Used to avoid offering the same domain twice running.
    public var recentArchetypes: [Archetype]
    /// Domains the user said they cared about during onboarding.
    public var preferredArchetypes: Set<Archetype>
    /// Set when the user tells us they are mid-scroll and want out.
    public var isDoomscrollRescue: Bool

    public init(
        energy: Int = 3,
        mood: Int = 3,
        timeBucket: TimeBucket = .evening,
        minutesToBedtime: Int = 120,
        recentCompletionRate: Double = 0.5,
        streakDays: Int = 0,
        recentArchetypes: [Archetype] = [],
        preferredArchetypes: Set<Archetype> = [],
        isDoomscrollRescue: Bool = false
    ) {
        self.energy = Swift.min(Swift.max(energy, 1), 5)
        self.mood = Swift.min(Swift.max(mood, 1), 5)
        self.timeBucket = timeBucket
        self.minutesToBedtime = minutesToBedtime
        self.recentCompletionRate = Swift.min(Swift.max(recentCompletionRate, 0), 1)
        self.streakDays = Swift.max(streakDays, 0)
        self.recentArchetypes = recentArchetypes
        self.preferredArchetypes = preferredArchetypes
        self.isDoomscrollRescue = isDoomscrollRescue
    }

    /// Key the bandit partitions its posteriors by. Kept deliberately coarse --
    /// a phone only ever sees one user, so finer buckets would never gather
    /// enough evidence to be worth anything.
    public var banditBucket: String {
        let energyBand = energy <= 2 ? "lo" : (energy >= 4 ? "hi" : "mid")
        return "\(timeBucket.rawValue)/\(energyBand)"
    }

    /// True when we are close enough to bed that only wind-down work belongs.
    public var isWindDownWindow: Bool { minutesToBedtime <= 45 }

    /// A hard ceiling on effort, as opposed to the ladder's soft target.
    ///
    /// The distinction matters: the ladder expresses "aim for about this
    /// much", and the grammar is allowed to drift a rung either way to keep
    /// its output varied. In three situations that drift is unacceptable and
    /// the cap has to actually bind --
    ///   - a rescue must be startable in ten seconds or the user goes back to
    ///     the feed,
    ///   - nothing near bedtime may be activating,
    ///   - on a flattened day, a big ask is worse than no ask.
    public var effortCeiling: Int {
        var ceiling = 5
        if isDoomscrollRescue { ceiling = Swift.min(ceiling, 2) }
        if isWindDownWindow { ceiling = Swift.min(ceiling, 3) }
        if energy <= 1 { ceiling = Swift.min(ceiling, 2) }
        return ceiling
    }
}
